# Generated by Django 5.0.6 on 2024-06-08 20:50

import common.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default=common.utils.default_image, null=True, upload_to=common.utils.upload_location),
        ),
    ]
