# Generated by Django 4.2.13 on 2024-06-19 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_comment_owner_alter_comment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
