# Generated by Django 4.2.13 on 2024-06-22 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_like_updated_at_alter_like_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='blog',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='blog.blog'),
        ),
    ]
