# Generated by Django 4.2.13 on 2024-08-24 17:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unreadchatroommessages',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='unreadchatroommessages',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
