# Generated by Django 4.2.13 on 2024-08-25 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_profile_created_at_profile_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='first_name'),
        ),
    ]
