# Generated by Django 4.2.13 on 2024-08-25 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_baseuser_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='last_name'),
        ),
    ]
